/// <reference types="next/image-types/global" />

// Declares `*.jpg` and friends as modules returning `StaticImageData`, so a
// realization's `import zdjecie01 from "./01.jpg"` type checks.
//
// `next-env.d.ts` carries the same reference, but it is generated by
// `next build`/`next dev` and gitignored, so it does not exist in a fresh
// checkout. `npm run typecheck` runs before anything generates it; in CI,
// that is the first step of the job. Committing the reference here keeps
// typecheck standalone rather than dependent on a build having happened first.
